name: bloc_builder
description: Util to easily create BLoC
version: 2.1.1
homepage: https://github.com/tanapoj/flutter_bloc_builder

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_live_data: ^2.1.1
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: