name: bloc_builder
description: Util to easily create BLoC
version: 1.0.1
author:
homepage: https://github.com/tanapoj/flutter_bloc_builder

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_live_data: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: